name: Test Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Start Docker Compose services
      - name: Start services with Docker Compose
        run: docker compose up -d
        env:
          NODE_ENV: test

      # Wait for services to be ready
      - name: Wait for services to be ready
        run: sleep 10

      - name: Run backend tests with Mocha
        run: pnpm run test

      - name: Publish Mocha Test Results
        if: always()
        run: npx github-actions-ctrf ctrf-report.json

      - name: Install Cypress
        run: pnpm add cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run --reporter json --reporter-options output=ctrf-cypress-report.json

      - name: Publish Cypress Test Results
        if: always()
        run: npx github-actions-ctrf ctrf-cypress-report.json

      # Stop Docker Compose services
      - name: Stop Docker Compose services
        run: docker compose down